name: Release App

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
            ext: ""
          - os: windows-latest
            rid: win-x64
            ext: ".exe"
          - os: macos-latest
            rid: osx-x64
            ext: ""
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Publish
        run: |
          chmod +x ./publish.sh
          ./publish.sh publish -v "${{ inputs.version }}" -a "${{ matrix.rid }}" -u
          find publish
        shell: bash

#      - name: Publish Application
#        run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true -o publish/${{ matrix.rid }}
#      
#      - name: Archive Binary
#        run: |
#          zip -r app-${{ matrix.rid }}.zip publish/${{ matrix.rid }}
#        shell: bash
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: app-${{ matrix.rid }}
#          path: app-${{ matrix.rid }}.zip

#  release:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download All Artifacts
#        uses: actions/download-artifact@v4
#        with:
#          path: artifacts
#
#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: artifacts/**/*
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
