name: Release App

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ${{ matrix.os }}
    #strategy:
    #  matrix:
    #    os: [ubuntu-latest, windows-latest, macos-latest]
    #    rid: [linux-x64, win-x64, osx-x64]  # Adjust as needed
    #    include:
    #      - os: ubuntu-latest
    #        ext: ""
    #      - os: windows-latest
    #        ext: ".exe"
    #      - os: macos-latest
    #        ext: ""
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Publish
        run: |
          dotnet --version
          ls -la
          ./publish.sh -h
        shell: bash

#      - name: Publish Application
#        run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true -o publish/${{ matrix.rid }}
#      
#      - name: Archive Binary
#        run: |
#          zip -r app-${{ matrix.rid }}.zip publish/${{ matrix.rid }}
#        shell: bash
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: app-${{ matrix.rid }}
#          path: app-${{ matrix.rid }}.zip

#  release:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download All Artifacts
#        uses: actions/download-artifact@v4
#        with:
#          path: artifacts
#
#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: artifacts/**/*
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
